[General]
; 这里填写你希望转换器默认使用的基础分流规则（例如使用开源的 ACL4SSR 规则）
base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini

[Proxy]
; 这里是关键！填写你当前的机场订阅链接。如果有多个，用逗号隔开
; 以后你更换机场，只需要回来修改下面这一行网址即可！
https://sub.murphyweb.cfd/game/hot/?token=d3958a006fdb97a39580d849545533d4





[Remote Config]
; 保持默认即可
